spring:
  application:
    name: hardware-assistant-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

app:
  jwt:
    secret: ${JWT_SECRET:local-dev-secret-key-minimum-256-bits-long-1234567890abcdef}
    expiration-ms: 86400000

  ai:
    groq-api-key: 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
    groq-base-url: https://api.groq.com
    model: llama-3.3-70b-versatile
#  ai:
#    gemini-api-key:  AIzaSyD8iTccKviD48LHi0byQEbQi5p88kfqJss
#    gemini-base-url: https://generativelanguage.googleapis.com
#    model: gemini-2.0-flash

  sms:
    africastalking-api-key: ${GEMINI_API_KEY:atsk_4d3675d384197b7dad108ba5200e80be7e2db4240c5af2fb67ad4670f2992427fd6ff4f3}
    africastalking-username: ${AT_USERNAME:sandbox}

  payment:
    paystack-secret-key: ${PAYSTACK_SECRET_KEY:sk_test_19550bc5e85b206bfaef74906127ae6e6c49cb1f}
    paystack-webhook-secret: ${PAYSTACK_WEBHOOK_SECRET:test}
