spring:
  application:
    name: hardware-assistant-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

app:
  jwt:
    secret: ${JWT_SECRET:local-dev-secret-key-minimum-256-bits-long-1234567890abcdef}
    expiration-ms: 86400000

  ai:
    groq-api-key: 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
    groq-base-url: https://api.groq.com
    model: llama-3.3-70b-versatile
#  ai:
#    gemini-api-key:  AIzaSyD8iTccKviD48LHi0byQEbQi5p88kfqJss
#    gemini-base-url: https://generativelanguage.googleapis.com
#    model: gemini-2.0-flash

  sms:
    africastalking-api-key: ${GEMINI_API_KEY:atsk_921377e0dc4f3f089610784ddee94ab3baf44361a14d9a31fda2c04293698967e88f89c9}
    africastalking-username: ${AT_USERNAME:sandbox}

  payment:
    paystack-secret-key: ${PAYSTACK_SECRET_KEY:sk_test_0547052f18ade4cb3e8b1f3116f343b0e2503e95}
    paystack-webhook-secret: ${PAYSTACK_WEBHOOK_SECRET:test}
