spring:
  config:
    import: optional:file:/.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/hardware_assistant_local
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true

logging:
  level:
    com.hardwareassistant: DEBUG
    org.springframework.security: DEBUG

server:
  port: 8080


app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000

  ai:
    groq-api-key: ${GROQ_API_KEY}
    groq-base-url: https://api.groq.com
    model: llama-3.3-70b-versatile

  sms:
    africastalking-api-key: ${GEMINI_API_KEY}
    africastalking-username: ${AT_USERNAME}

  payment:
    paystack-secret-key: ${PAYSTACK_SECRET_KEY}
    paystack-webhook-secret: ${PAYSTACK_WEBHOOK_SECRET}